#ifndef DILITHIUM_PARAMS_H
#define DILITHIUM_PARAMS_H

#define DILITHIUM_MODE 5

#define DILITHIUM_K 8
#define DILITHIUM_L 7
#define DILITHIUM_ETA 2
#define DILITHIUM_TAU 60
#define DILITHIUM_BETA 120
#define DILITHIUM_GAMMA1 ((1U << 19))
#define DILITHIUM_GAMMA2 ((DILITHIUM_Q - 1) / 32)
#define DILITHIUM_OMEGA 75

#define DILITHIUM_POLY_UNIFORM_ETA_PACKEDBYTES 96
#define DILITHIUM_POLYZ_PACKEDBYTES 640
#define DILITHIUM_POLYW1_PACKEDBYTES 128

#define DILITHIUM_POLYT1_PACKEDBYTES 320
#define DILITHIUM_POLYT0_PACKEDBYTES 416
#define DILITHIUM_POLYVECH_PACKEDBYTES (DILITHIUM_OMEGA + DILITHIUM_K)

#define DILITHIUM_CRYPTO_PUBLICKEYBYTES (32 + DILITHIUM_L * DILITHIUM_POLYT1_PACKEDBYTES)
#define DILITHIUM_CRYPTO_SECRETKEYBYTES (2 * 32 + DILITHIUM_L * 32 + DILITHIUM_K * 32 + DILITHIUM_K * DILITHIUM_POLYT0_PACKEDBYTES + DILITHIUM_L * DILITHIUM_POLYT0_PACKEDBYTES)
#define DILITHIUM_CRYPTO_BYTES (32 + DILITHIUM_L * DILITHIUM_POLY_UNIFORM_ETA_PACKEDBYTES + DILITHIUM_POLYVECH_PACKEDBYTES)

#endif
