#ifndef KYBER_PARAMS_H
#define KYBER_PARAMS_H

#define KYBER_N 256
#define KYBER_Q 3329

#define KYBER_K 4
#define KYBER_ETA1 2
#define KYBER_ETA2 2

#define KYBER_POLY_BYTES 384
#define KYber_POLY_COMPRESSED_BYTES 128

#define KYBER_POLYVEC_BYTES (KYBER_K * KYBER_POLY_BYTES)
#define KYBER_POLYVEC_COMPRESSED_BYTES (KYBER_K * 320)

#define KYBER_INDCPA_PUBLICKEYBYTES (KYBER_POLYVEC_BYTES + 32)
#define KYBER_INDCPA_SECRETKEYBYTES (KYBER_POLYVEC_BYTES)
#define KYBER_INDCPA_BYTES (KYBER_POLYVEC_COMPRESSED_BYTES + KYber_POLY_COMPRESSED_BYTES)

#define KYBER_PUBLICKEYBYTES (KYBER_INDCPA_PUBLICKEYBYTES)
#define KYBER_SECRETKEYBYTES (KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + 64)
#define KYBER_CIPHERTEXTBYTES (KYBER_INDCPA_BYTES)

#endif
