name: CI

on:
  push:
  pull_request:

jobs:
  # Main build and smoke test
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang lld nasm make grub-pc-bin xorriso mtools qemu-system-x86
      
      - name: Build kernel and ISO
        run: make -j$(nproc) iso
        
      - name: Generate SBOM
        run: make sbom
        
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: dist/sbom.txt
      
      - name: Smoke boot in QEMU (headless)
        run: |
          qemu-system-x86_64 -m 512M -cdrom dist/limitlessos.iso -nographic -serial mon:stdio -boot d -no-reboot &
          PID=$!
          # Wait up to 20s for a recognizable kernel message
          for i in $(seq 1 40); do
            sleep 0.5
            if grep -q "Init: launching" <(tail -n +1 -f /proc/$PID/fd/1 2>/dev/null & sleep 0.5; kill $! 2>/dev/null); then
              echo "Boot message detected"
              kill $PID || true
              exit 0
            fi
          done
          echo "Boot message not detected"
          kill $PID || true
          exit 1
  
  # Sanitizer builds (KASAN/UBSAN)
  sanitizer-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang lld nasm make
      
      - name: Build with ${{ matrix.sanitizer }} sanitizer
        run: |
          # Note: Full sanitizer support requires kernel changes
          # For now, build with sanitizer flags for userspace components
          CFLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer -g" make -j$(nproc) kernel || true
        continue-on-error: true
      
      - name: Report sanitizer build status
        run: |
          echo "Sanitizer build completed for: ${{ matrix.sanitizer }}"
          echo "Full sanitizer support will be implemented in M2/M3"
  
  # Reproducibility check
  reproducibility-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang lld nasm make grub-pc-bin xorriso mtools
      
      - name: First build
        run: |
          export SOURCE_DATE_EPOCH=1697328000
          make clean
          make -j$(nproc) kernel
          cp build/limitless.elf limitless-build1.elf
      
      - name: Second build
        run: |
          export SOURCE_DATE_EPOCH=1697328000
          make clean
          make -j$(nproc) kernel
          cp build/limitless.elf limitless-build2.elf
      
      - name: Compare builds
        run: |
          if cmp -s limitless-build1.elf limitless-build2.elf; then
            echo "✅ Builds are reproducible (bit-for-bit identical)"
            exit 0
          else
            echo "⚠️  Builds differ - reproducibility needs improvement"
            sha256sum limitless-build1.elf limitless-build2.elf
            # Don't fail the build yet, this is informational
            exit 0
          fi

